version: "3.8"
services: 
  k8scourse-db:
    image: mysql:5.7
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=mysql
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - "./db/init.sql:/docker-entrypoint-initdb.d/init.sql"
    networks:
      - k8scourse
  back:
    image: joellord/k8scourse-back:1
    ports:
      - "3000:3000"
    networks:
      - k8scourse
    environment:
      - MYSQL_HOST=k8scourse-db
  front:
    image: joellord/k8scourse-front:1
    ports:
      - "8080:8080"
    environment:
      - BASE_URL=http://localhost:3000

networks:
  k8scourse:
