apiVersion: v1
kind: PersistentVolume
metadata:
  name: micro-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: micro-pvc2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microback
spec:
  template:
    metadata:
      labels:
        app: k8scourse-demo
        role: backend
        microservice: microback
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: microback
          image: joellord/k8scourse-microback
          env:
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_USER
              value: user
            - name: MYSQL_PASS
              value: mysql
            - name: GIF_CAPTION_SVC
              value: microgifcap
            - name: IMAGE_PATH
              value: /tmp/gifcaptionizer
          volumeMounts:
            - name: micro-storage
              mountPath: /tmp/gifcaptionizer
      volumes:
        - name: micro-storage
          persistentVolumeClaim:
            claimName: micro-pvc2
  selector:
    matchLabels:
      microservice: microback
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microgifcap
spec:
  template:
    metadata:
      labels:
        app: k8scourse-demo
        role: backend
        microservice: microgifcap
    spec:
      containers:
        - name: microgifcap
          image: joellord/k8scourse-microgifcap
          env:
            - name: IMAGE_PATH
              value: /tmp/gifcaptionizer
          volumeMounts:
            - name: micro-storage
              mountPath: /tmp/gifcaptionizer
      volumes:
        - name: micro-storage
          persistentVolumeClaim:
            claimName: micro-pvc2
  selector:
    matchLabels:
      microservice: microgifcap
  replicas: 4
---
apiVersion: v1
kind: Service
metadata:
  name: microback
  labels:
    role: backend
    microservice: microback
spec:
  selector:
    microservice: microback
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: microgifcap
  labels:
    role: backend
    microservice: microgifcap
spec:
  selector:
    microservice: microgifcap
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: main
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: microback
              servicePort: 80
            path: /api(/|$)(.*)
            pathType: Prefix
          - backend:
              serviceName: k8scourse-front
              servicePort: 80
            path: /()(.*)
